import { createHash } from "node:crypto";
import type {
  ChunkOptions,
  CodeChunk,
  DetectionResult,
  LanguageAdapter,
  LanguageReviewProfile,
  ParseInput,
  ParsedDocument,
  ProjectContext,
  RepositoryFile,
  ReviewRule,
  SuggestionInput,
  SymbolEdge,
  SymbolRecord,
  TestLink,
  ValidationResult,
} from "./base";

export class GoAdapter implements LanguageAdapter {
  readonly id = "go-adapter";
  readonly version = "2026-08-20.1";
  readonly language = "go" as const;

  detect(file: RepositoryFile): DetectionResult {
    return {
      language: "go",
      isGenerated: file.path.endsWith(".pb.go") || (file.content?.includes("Code generated by") ?? false),
      isTest: file.path.endsWith("_test.go"),
      confidence: 0.99,
    };
  }

  async parse(input: ParseInput): Promise<ParsedDocument> {
    const lines = input.source.replace(/\r\n/g, "\n").split("\n");
    return {
      path: input.path,
      language: "go",
      source: input.source,
      lines,
      ast: { type: "SourceFile", startLine: 1, endLine: lines.length },
      isGenerated: input.path.endsWith(".pb.go") || input.source.includes("Code generated by"),
      isTest: input.path.endsWith("_test.go"),
      syntaxValid: true,
      parseErrors: [],
    };
  }

  chunk(document: ParsedDocument): CodeChunk[] {
    const lines = document.lines;
    const chunks: CodeChunk[] = [];
    const maxLines = 100;
    const overlap = 15;

    for (let start = 0; start < lines.length; start += maxLines - overlap) {
      const end = Math.min(lines.length, start + maxLines);
      const content = lines.slice(start, end).join("\n");
      if (content.trim().length === 0) continue;

      let symbol: string | null = null;
      for (let i = start; i >= Math.max(0, start - 30); i -= 1) {
        const line = lines[i]?.trim() ?? "";
        const fnMatch = /^func\s+(?:\([^)]*\)\s*)?([A-Za-z0-9_]+)/.exec(line);
        const typeMatch = /^type\s+([A-Za-z0-9_]+)\s+/.exec(line);
        if (fnMatch?.[1]) {
          symbol = fnMatch[1];
          break;
        }
        if (typeMatch?.[1]) {
          symbol = typeMatch[1];
          break;
        }
      }

      chunks.push({
        path: document.path,
        language: document.language,
        symbol,
        startLine: start + 1,
        endLine: end,
        content,
        contentHash: createHash("sha256")
          .update(`${document.path}:${start + 1}:${content}`)
          .digest("hex"),
      });
      if (end === lines.length) break;
    }
    return chunks;
  }

  symbols(document: ParsedDocument): SymbolRecord[] {
    const records: SymbolRecord[] = [];
    const lines = document.lines;

    for (let i = 0; i < lines.length; i += 1) {
      const line = lines[i]?.trim() ?? "";
      const lineNum = i + 1;

      const funcMatch = /^func\s+(\((?:[^)]+)\)\s+)?([A-Za-z0-9_]+)\s*\(([^)]*)\)/.exec(line);
      if (funcMatch?.[2]) {
        records.push({
          name: funcMatch[2],
          kind: funcMatch[1] ? "method" : "function",
          path: document.path,
          startLine: lineNum,
          endLine: lineNum,
          signature: line,
          isExported: /^[A-Z]/.test(funcMatch[2]),
        });
        continue;
      }

      const typeMatch = /^type\s+([A-Za-z0-9_]+)\s+(struct|interface)/.exec(line);
      if (typeMatch?.[1]) {
        records.push({
          name: typeMatch[1],
          kind: typeMatch[2] === "interface" ? "interface" : "struct",
          path: document.path,
          startLine: lineNum,
          endLine: lineNum,
          signature: line,
          isExported: /^[A-Z]/.test(typeMatch[1]),
        });
        continue;
      }
    }
    return records;
  }

  edges(document: ParsedDocument, _project: ProjectContext): SymbolEdge[] {
    const edges: SymbolEdge[] = [];
    let inImportBlock = false;

    for (const line of document.lines) {
      const trimmed = line.trim();
      if (trimmed.startsWith("import (")) {
        inImportBlock = true;
        continue;
      }
      if (inImportBlock && trimmed === ")") {
        inImportBlock = false;
        continue;
      }
      if (inImportBlock) {
        const match = /^"([^"]+)"/.exec(trimmed);
        if (match?.[1]) {
          const pkg = match[1];
          const target = pkg.split("/").at(-1) ?? pkg;
          edges.push({
            sourceSymbol: document.path,
            targetSymbol: target,
            sourcePath: document.path,
            targetPath: pkg,
            kind: "imports",
          });
        }
      } else {
        const singleImport = /^import\s+"([^"]+)"/.exec(trimmed);
        if (singleImport?.[1]) {
          const pkg = singleImport[1];
          const target = pkg.split("/").at(-1) ?? pkg;
          edges.push({
            sourceSymbol: document.path,
            targetSymbol: target,
            sourcePath: document.path,
            targetPath: pkg,
            kind: "imports",
          });
        }
      }
    }
    return edges;
  }

  async projectContext(files: RepositoryFile[]): Promise<ProjectContext> {
    const paths = files.map((f) => f.path);
    const manifests = paths.filter((p) => p.endsWith("go.mod") || p.endsWith("go.sum") || p.endsWith("go.work"));
    const frameworks: string[] = [];
    if (paths.some((p) => p.includes("gin-gonic"))) frameworks.push("gin");
    if (paths.some((p) => p.includes("fiber"))) frameworks.push("fiber");
    if (paths.some((p) => p.includes("echo"))) frameworks.push("echo");
    if (paths.some((p) => p.includes("grpc"))) frameworks.push("grpc");

    return {
      rootFiles: paths.filter((p) => !p.includes("/")),
      manifests,
      packageManager: "go modules",
      frameworks,
    };
  }

  testLinks(document: ParsedDocument, project: ProjectContext): TestLink[] {
    const links: TestLink[] = [];
    if (!document.isTest) {
      const testFile = document.path.replace(/\.go$/, "_test.go");
      if (project.rootFiles.includes(testFile)) {
        links.push({ sourcePath: document.path, testPath: testFile, confidence: 0.99 });
      }
    }
    return links;
  }

  reviewProfile(): LanguageReviewProfile {
    return {
      language: "go",
      idioms: [
        "Explicit error handling: if err != nil",
        "defer resp.Body.Close() after checking error",
        "Context cancellation propagation",
        "Avoid goroutine leaks",
      ],
      dangerousPatterns: [
        "defer resp.Body.Close() before checking err != nil",
        "exec.Command(rawUserString)",
        "Ignoring errors with _ assignment on critical calls",
        "Data race on uncoordinated map writes across goroutines",
      ],
      securityChecks: ["Command injection via exec.Command", "Path traversal", "SQL injection in database/sql"],
      concurrencyConsiderations: [
        "Concurrent map read/write causes fatal crash",
        "Goroutines that never terminate without context cancel",
        "sync.WaitGroup Add inside goroutine instead of outside",
      ],
      resourceManagementRules: [
        "Always close http.Response.Body",
        "Always close sql.Rows and os.File",
      ],
      testingFrameworks: ["testing", "testify", "ginkgo"],
      rules: [
        {
          id: "go-resp-body-close-order",
          category: "correctness",
          severity: "high",
          description: "Ensure error check precedes defer resp.Body.Close()",
          check: (doc) => {
            const findings: ReturnType<ReviewRule["check"]> = [];
            for (let i = 0; i < doc.lines.length - 1; i += 1) {
              const line = doc.lines[i]?.trim() ?? "";
              const nextLine = doc.lines[i + 1]?.trim() ?? "";
              if (line.includes("http.Get(") || line.includes("http.Post(")) {
                if (nextLine.startsWith("defer ") && nextLine.includes(".Body.Close()")) {
                  findings.push({
                    title: "Nil pointer dereference risk on HTTP response error",
                    explanation: "defer resp.Body.Close() must come AFTER if err != nil check, otherwise nil resp causes panic.",
                    line: i + 2,
                    evidence: nextLine,
                  });
                }
              }
            }
            return findings;
          },
        },
      ],
    };
  }

  validateSuggestion(input: SuggestionInput): ValidationResult {
    return { valid: Boolean(input.suggestedPatch.trim()), errors: [] };
  }
}
